name: EligiusNametag
description: Custom nametags plugin
version: ${version}
main: com.makrozai.eligiusnametag.EligiusNametag
api-version: '1.21'
authors:
  - makrozai

dependencies:
    server:
      PlaceholderAPI:
        load: BEFORE
        required: false
        join-classpath: true
      Vault:
        load: BEFORE
        required: false
        join-classpath: true